/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.details.management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */

public class studentdetails extends javax.swing.JFrame {

    /**
     * Creates new form studentdetails
     */
        Connection conn=null;
    public studentdetails() throws SQLException {
        initComponents();
        conn =DBconnect.connect();
        PreparedStatement pstmt=null;
        ResultSet rs=null;
        try
        {
            pstmt=conn.prepareStatement("select * from `table`");
            
            rs=pstmt.executeQuery();
            boolean f=true;
            while(rs.next())
            {
                
                String s1=rs.getString("regno");
                if(s1.equals(info))
                {
                   name.setText(rs.getString("name"));
                   gender.setText(rs.getString("gender"));
                   branch.setText(rs.getString("branch"));
                   cgpa.setText(rs.getString("cgpa"));
                   year.setText(rs.getString("year"));
                   attendance.setText(rs.getString("attendance"));
                   regno.setText(rs.getString("regno"));
                   town.setText(rs.getString("city"));
                   phno.setText(rs.getString("phoneno"));
                   f=false;
                   break;
                }
            }
            if(f)
            {
                JOptionPane.showMessageDialog(null,"Registration number not found ");
                JOptionPane.showMessageDialog(null," Please Press Back Button and enter valid Number");
                
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        branch = new javax.swing.JLabel();
        regno = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        phno = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        cgpa = new javax.swing.JLabel();
        attendance = new javax.swing.JLabel();
        town = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Name ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 70, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Branch");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 130, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Registation no");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 200, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(330, 70, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Phone no");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(330, 130, 70, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Year");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(330, 200, 70, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("CGPA");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(570, 70, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Attendance");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(570, 130, 90, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("City/Town");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(570, 200, 70, 30);

        jButton1.setBackground(new java.awt.Color(51, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 320, 90, 30);

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 153));
        name.setText("invalid");
        jPanel1.add(name);
        name.setBounds(190, 70, 110, 30);

        branch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        branch.setForeground(new java.awt.Color(0, 0, 153));
        branch.setText("invalid");
        jPanel1.add(branch);
        branch.setBounds(190, 140, 90, 20);

        regno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        regno.setForeground(new java.awt.Color(0, 0, 153));
        regno.setText("invalid");
        jPanel1.add(regno);
        regno.setBounds(190, 204, 120, 20);

        gender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 0, 153));
        gender.setText("invalid");
        jPanel1.add(gender);
        gender.setBounds(440, 70, 80, 20);

        phno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        phno.setForeground(new java.awt.Color(0, 0, 153));
        phno.setText("invalid");
        jPanel1.add(phno);
        phno.setBounds(440, 130, 110, 30);

        year.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        year.setForeground(new java.awt.Color(0, 0, 153));
        year.setText("invalid");
        jPanel1.add(year);
        year.setBounds(440, 200, 90, 30);

        cgpa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cgpa.setForeground(new java.awt.Color(0, 0, 153));
        cgpa.setText("invalid");
        jPanel1.add(cgpa);
        cgpa.setBounds(700, 70, 70, 30);

        attendance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        attendance.setForeground(new java.awt.Color(0, 0, 153));
        attendance.setText("invalid");
        jPanel1.add(attendance);
        attendance.setBounds(700, 130, 80, 30);

        town.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        town.setForeground(new java.awt.Color(0, 0, 153));
        town.setText("invalid");
        jPanel1.add(town);
        town.setBounds(700, 200, 130, 30);

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\w1.jpg")); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(0, 0, 960, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
                Student stu=new Student();
                stu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     */
        public static String info;

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        info=args[0];
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
           try {
               new studentdetails().setVisible(true);
           } catch (SQLException ex) {
               Logger.getLogger(studentdetails.class.getName()).log(Level.SEVERE, null, ex);
           }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attendance;
    private javax.swing.JLabel branch;
    private javax.swing.JLabel cgpa;
    private javax.swing.JLabel gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phno;
    private javax.swing.JLabel regno;
    private javax.swing.JLabel town;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
